Repository jenkins-x/dev-env, pull requests merged in 2019-07, with the labels that each got.

#40 chore: Upgrade dev-env-base to 0.0.23
  dev-env
Labels: approved, size/XS

#41 chore: Updated to use 0.0.24 of dev-env-base
  dev-env
Labels: approved, size/XS

#42 feat: dev-env-base version variable
  dev-env
Labels: approved, lgtm, size/XS

#53 chore: Update go version in doc
  README.md
Labels: approved, size/XS

#81 fix: don't assume the cpu and memory can be default
  .pre-commit-config.yaml
  dev-env
Labels: approved, size/XS

#80 fix: ensures all mounted directories exist before mounting them
  dev-env
Labels: approved, size/XS

#79 feat: adds the ability to customize env variables
  .gitignore
  dev-env
Labels: approved, size/XS

#86 fix: added missing mounted files
  dev-env
Labels: approved, size/S

#91 fix: correct bash history filename
  dev-env
Labels: approved, size/XS

#94 fix: ensure host kubeconfig can be used in dev-env
  dev-env
Labels: approved, lgtm, size/S

#105 fix: MOUNT dir
  dev-env
Labels: size/XS

#106 fix: Added .kube mount to docker run
  dev-env
Labels: approved, size/XS

#107 fix: stop recursive copy of .kube
  dev-env
Labels: approved, size/XS

#120 fix: ensure .kube directory has the correct permissions
  dev-env
Labels: approved, size/XS

#111 chore: Add memory requests/limits to pipeline
  jenkins-x.yml
Labels: approved, size/S

#138 chore: added .secrets.baseline
  .secrets.baseline
Labels: approved, lgtm, size/M
