Repository jenkins-x/dev-env, pull requests merged in 2019-03, with the labels that each got.

#7 Initial tekton pipeline
  Makefile
  jenkins-x.yml
Labels: approved

#8 Removed build-arg from makefile
  .makerc
  Makefile
Labels: approved, size/S

#9 Added kubernetes secrets decoder
  Dockerfile
Labels: approved, size/XS

#10 Added jx release version
  Dockerfile
Labels: approved, size/XS

#11 Update dev-env to gcr.io/jenkinsxio/dev-env:0.0.4
  dev-env
Labels: approved, size/XS

#12 Removed reference to cagiti
  Makefile
  README.md
  docs/goland.md
Labels: approved, size/XS

#13 Added bash completion package
  Dockerfile
Labels: approved, size/XS

#16 Change weather & time format in statusbar
  env/cloud/.tmux.conf.local
  env/mac/.tmux.conf.local
Labels: approved, size/XS

#17 Add hugo to the dev-env
  Dockerfile
  dev-env
Labels: approved, size/XS

#18 Added drill for dns exloration
  Dockerfile
Labels: approved, size/XS

#19 Update README.md to include XQuartz preferences
  README.md
Labels: approved, ok-to-test, size/XS
