Repository jenkins-x/dev-env, pull requests merged in 2019-05, with the labels that each got.

#22 Updated kaniko secret name and key
  Dockerfile
  jenkins-x.yml
Labels: approved, size/S

#23 Updated to use dev-env-base docker container
  dev-env
Labels: approved, size/M

#24 Removed goland script and added command support into goland doc
  README.md
  docs/goland.md
  goland
Labels: approved, size/M

#25 Upsert env files
  dev-env
Labels: approved, size/S

#26 Update dev-env-base image to 0.0.9
  dev-env
Labels: approved, size/XS

#27 Adding information on goland running on ubuntu using a container
  docs/goland.md
Labels: approved, size/S

#28 Update dev-env-base to 0.0.10
  dev-env
Labels: approved, size/XS

#29 Updated dev-env-base to 0.0.12
  dev-env
Labels: approved, size/XS

#31 Updated dev-env-base to 0.0.13
  dev-env
Labels: approved, size/XS

#33 Updated dev-env-base to 0.0.15
  dev-env
Labels: size/XS
